/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Carbon Window Manager
 #	author : miyako
 #	2015/02/06
 #
 # --------------------------------------------------------------------------------*/



// --- Visual Attributes
void CWM_SET_MODIFIED(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_Get_modified(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_SET_ZOOM_BOX(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_Get_zoom_box(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_SET_CLOSE_BOX(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_Get_close_box(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_SET_COLLAPSE_BOX(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_Get_collapse_box(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_SET_WINDOW_ICON(sLONG_PTR *pResult, PackagePtr pParams);
void CWM_Get_window_icon(sLONG_PTR *pResult, PackagePtr pParams);
